apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogeyJhdXRoIjogIllXdHlZWE51YVd0dmRqYzVPbWRvY0Y5aGJscFdNRTFXVERWbVpUTmlNRVJxY21aTE5td3dURXBSZW5vNFdXb3pabVV5TTBJPSJ9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==
type: kubernetes.io/dockerconfigjson
