apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZV3R5WVhOdWFXdHZkamM1T21kcGRHaDFZbDl3WVhSZk1URkNVRlUxU0RSUk1FSTVTVWxqTTFGeVdrUk9TMTloWlZNellVcEdhazk2WkZRd2VFeHdXbWhKTlVWSWREVlBaMnAxTWtwV2RuRXhjVE4yTkRjNFVHcEdURXMzVFVKTVVVUnJiM3B1ZDFwb1V3PT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
