apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYWtyYXNuaWtvdjc5IiwicGFzc3dvcmQiOiJnaXRodWJfcGF0XzExQlBVNUg0UTBiQUUzbnk4MmFyVjdfeDdLYmVvZHlORFZaMERyU2RidXJXZ2s3UDFBWGpWZzFmOEFjWkVEek1xTUdLRjZORTdZVm0xVnRJd1QiLCJhdXRoIjoiWVd0eVlYTnVhV3R2ZGpjNU9tZHBkR2gxWWw5d1lYUmZNVEZDVUZVMVNEUlJNR0pCUlROdWVUZ3lZWEpXTjE5NE4wdGlaVzlrZVU1RVZsb3dSSEpUWkdKMWNsZG5hemRRTVVGWWFsWm5NV1k0UVdOYVJVUjZUWEZOUjB0R05rNUZOMWxXYlRGV2RFbDNWQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2026-03-29T16:30:07Z"
  name: dockerconfigjson
  namespace: cinemaabyss
  resourceVersion: "2014"
  uid: c72837e9-aaeb-417a-8b30-9588d33096b8
type: kubernetes.io/dockerconfigjson
